# Generated by Django 6.0.4 on 2026-05-12 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehae_accommodation_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('merchant_type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('verification_document', models.FileField(upload_to='merchant_docs/')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
