# Generated by Django 6.0.4 on 2026-05-13 10:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lehae_accommodation_app', '0003_accreditation_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='property',
            old_name='price',
            new_name='monthly_rent',
        ),
        migrations.AddField(
            model_name='property',
            name='accommodation_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Sharing', 'Sharing'), ('House', 'House'), ('Hostel', 'Hostel'), ('Rooms', 'Rooms')], default='Single Room', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='available_from',
            field=models.DateField(default=datetime.date(2026, 5, 13)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='beds_available',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='cover_image',
            field=models.ImageField(default='property_covers/default.jpg', upload_to='property_covers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='house_policy',
            field=models.FileField(blank=True, null=True, upload_to='property_documents/policies/'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_rooms',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='proof_of_accreditation',
            field=models.FileField(blank=True, null=True, upload_to='property_documents/accreditation/'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(default='Free State', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='accreditation',
            field=models.ManyToManyField(blank=True, to='lehae_accommodation_app.accreditation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='lehae_accommodation_app.merchant'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='lehae_accommodation_app.amenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='campuses',
            field=models.ManyToManyField(blank=True, to='lehae_accommodation_app.campus'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_gallery/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='lehae_accommodation_app.property')),
            ],
        ),
    ]
